with api_seed(path, description, api_group, method) as (
    values
        ('/api/auth/logout', 'User logout', 'auth', 'POST'),
        ('/api/users/me', 'Get current user', 'user', 'GET'),
        ('/api/users/me', 'Update current user', 'user', 'PUT'),
        ('/api/users/me/password', 'Change current user password', 'user', 'PUT'),
        ('/api/users/me/settings', 'Update current user settings', 'user', 'PUT'),
        ('/api/users/me/authority', 'Switch current user role', 'user', 'PUT'),
        ('/api/users', 'List users', 'user', 'GET'),
        ('/api/users', 'Create user', 'user', 'POST'),
        ('/api/users/{id}', 'Update user', 'user', 'PUT'),
        ('/api/users/{id}', 'Delete user', 'user', 'DELETE'),
        ('/api/users/{id}/password/reset', 'Reset user password', 'user', 'POST'),
        ('/api/users/{id}/authorities', 'Update user roles', 'user', 'PUT'),
        ('/api/menus/current', 'Get menus', 'menu', 'GET'),
        ('/api/menus', 'List menus', 'menu', 'GET'),
        ('/api/menus', 'Create menu', 'menu', 'POST'),
        ('/api/menus/tree', 'Get menu tree', 'menu', 'GET'),
        ('/api/menus/role-matrix', 'Get menu role matrix', 'menu', 'GET'),
        ('/api/menus/{id}', 'Get menu', 'menu', 'GET'),
        ('/api/menus/{id}', 'Update menu', 'menu', 'PUT'),
        ('/api/menus/{id}', 'Delete menu', 'menu', 'DELETE'),
        ('/api/menus/{id}/roles', 'Get menu roles', 'menu', 'GET'),
        ('/api/menus/{id}/roles', 'Update menu roles', 'menu', 'PUT'),
        ('/api/menus/authority', 'Get role menus', 'menu', 'GET'),
        ('/api/menus/authority', 'Add role menus', 'menu', 'POST'),
        ('/api/menus/authority', 'Update role menus', 'menu', 'PUT'),
        ('/api/roles', 'List roles', 'role', 'GET'),
        ('/api/roles', 'Create role', 'role', 'POST'),
        ('/api/roles/{authority_id}', 'Update role', 'role', 'PUT'),
        ('/api/roles/{authority_id}', 'Delete role', 'role', 'DELETE'),
        ('/api/roles/{authority_id}/users', 'Get role users', 'role', 'GET'),
        ('/api/roles/{authority_id}/users', 'Update role users', 'role', 'PUT'),
        ('/api/roles/data-authority', 'Update role data authority', 'role', 'PUT'),
        ('/api/routes', 'List APIs', 'api', 'GET'),
        ('/api/routes', 'Create API', 'api', 'POST'),
        ('/api/routes/all', 'List all APIs', 'api', 'GET'),
        ('/api/routes/groups', 'List API groups', 'api', 'GET'),
        ('/api/routes/casbin/refresh', 'Refresh API policies', 'api', 'POST'),
        ('/api/routes/authority', 'Get role APIs', 'api', 'GET'),
        ('/api/routes/role-matrix', 'Get API role matrix', 'api', 'GET'),
        ('/api/routes/roles', 'Get API roles', 'api', 'GET'),
        ('/api/routes/roles', 'Update API roles', 'api', 'PUT'),
        ('/api/routes/{id}', 'Get API', 'api', 'GET'),
        ('/api/routes/{id}', 'Update API', 'api', 'PUT'),
        ('/api/routes/{id}', 'Delete API', 'api', 'DELETE'),
        ('/api/routes/batch', 'Delete APIs', 'api', 'DELETE'),
        ('/api/attachment-categories', 'List attachment categories', 'file', 'GET'),
        ('/api/attachment-categories', 'Create attachment category', 'file', 'POST'),
        ('/api/attachment-categories/{id}', 'Delete attachment category', 'file', 'DELETE'),
        ('/api/files', 'List files', 'file', 'GET'),
        ('/api/files/import-url', 'Import file URL', 'file', 'POST'),
        ('/api/files/upload', 'Upload file', 'file', 'POST'),
        ('/api/files/{id}', 'Delete file', 'file', 'DELETE'),
        ('/api/files/{id}/name', 'Rename file', 'file', 'PATCH'),
        ('/api/params', 'List params', 'params', 'GET'),
        ('/api/params', 'Create param', 'params', 'POST'),
        ('/api/params/by-key', 'Get param by key', 'params', 'GET'),
        ('/api/params/batch', 'Delete params', 'params', 'DELETE'),
        ('/api/params/{id}', 'Get param', 'params', 'GET'),
        ('/api/params/{id}', 'Update param', 'params', 'PUT'),
        ('/api/params/{id}', 'Delete param', 'params', 'DELETE'),
        ('/api/dictionaries', 'List dictionaries', 'dictionary', 'GET'),
        ('/api/dictionaries', 'Create dictionary', 'dictionary', 'POST'),
        ('/api/dictionaries/import', 'Import dictionary', 'dictionary', 'POST'),
        ('/api/dictionaries/{id}', 'Get dictionary', 'dictionary', 'GET'),
        ('/api/dictionaries/{id}', 'Update dictionary', 'dictionary', 'PUT'),
        ('/api/dictionaries/{id}', 'Delete dictionary', 'dictionary', 'DELETE'),
        ('/api/dictionaries/{id}/export', 'Export dictionary', 'dictionary', 'GET'),
        ('/api/dictionaries/{id}/details/tree', 'Get dictionary details tree', 'dictionary', 'GET'),
        ('/api/dictionary-details', 'Create dictionary detail', 'dictionary', 'POST'),
        ('/api/dictionary-details/tree-by-type', 'Get dictionary detail tree by type', 'dictionary', 'GET'),
        ('/api/dictionary-details/by-parent', 'Get dictionary details by parent', 'dictionary', 'GET'),
        ('/api/dictionary-details/{id}', 'Get dictionary detail', 'dictionary', 'GET'),
        ('/api/dictionary-details/{id}', 'Update dictionary detail', 'dictionary', 'PUT'),
        ('/api/dictionary-details/{id}', 'Delete dictionary detail', 'dictionary', 'DELETE'),
        ('/api/dictionary-details/{id}/path', 'Get dictionary detail path', 'dictionary', 'GET'),
        ('/api/login-logs', 'List login logs', 'logs', 'GET'),
        ('/api/login-logs', 'Delete login logs', 'logs', 'DELETE'),
        ('/api/login-logs/{id}', 'Get login log', 'logs', 'GET'),
        ('/api/login-logs/{id}', 'Delete login log', 'logs', 'DELETE'),
        ('/api/operation-logs', 'List operation logs', 'logs', 'GET'),
        ('/api/operation-logs', 'Delete operation logs', 'logs', 'DELETE'),
        ('/api/operation-logs/{id}', 'Delete operation log', 'logs', 'DELETE'),
        ('/api/system/config', 'Get system config', 'system', 'GET'),
        ('/api/system/config', 'Update system config', 'system', 'PUT'),
        ('/api/system/server-info', 'Get server info', 'system', 'GET'),
        ('/api/system/reload', 'Reload system', 'system', 'POST')
)
insert into sys_apis (path, description, api_group, method)
select path, description, api_group, method
from api_seed
on conflict (path, method) do update
set description = excluded.description,
    api_group = excluded.api_group;

insert into sys_role_apis (authority_id, api_id)
select 888, id
from sys_apis
on conflict do nothing;
